# Generated by Django 4.1.5 on 2023-02-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_input_paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_send_id', models.CharField(max_length=255)),
                ('date_deliver', models.DateField()),
                ('no_andikator', models.CharField(max_length=255)),
                ('type_paper_id', models.CharField(max_length=255)),
                ('date_paper', models.DateField()),
                ('date_andikator', models.DateField()),
                ('user_deliver_id', models.CharField(max_length=255)),
                ('no_paper_deliver', models.CharField(max_length=255)),
                ('permination', models.CharField(max_length=255)),
                ('mozo', models.CharField(max_length=255)),
                ('tozihat', models.CharField(max_length=500)),
                ('photo_paper', models.CharField(max_length=255)),
                ('peyvast', models.CharField(max_length=255)),
            ],
        ),
    ]
