# Generated by Django 4.1.5 on 2023-02-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_kanon_perm'),
    ]

    
