# Generated by Django 4.1.5 on 2023-02-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_t_input_paper_peyvast_file_t_input_paper_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_input_paper',
            name='peyvast_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='t_input_paper',
            name='photo_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
