# Generated by Django 4.1.5 on 2023-02-11 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0009_bar_bartime'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_user_erja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_send_id', models.CharField(max_length=255)),
                ('date_send', models.DateField()),
                ('date_see', models.DateField()),
                ('T_input_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.t_input_paper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
