# Generated by Django 4.1.5 on 2023-02-11 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_t_user_erja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_user_erja',
            old_name='user',
            new_name='user_deliver_id',
        ),
    ]
