# Generated by Django 4.1.5 on 2023-02-11 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_rename_user_t_user_erja_user_deliver_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_user_erja',
            old_name='T_input_paper',
            new_name='paper_id',
        ),
    ]
