# Generated by Django 4.1.5 on 2023-02-11 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_rename_t_input_paper_t_user_erja_paper_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_user_erja',
            old_name='paper_id',
            new_name='paper',
        ),
        migrations.RenameField(
            model_name='t_user_erja',
            old_name='user_deliver_id',
            new_name='user_deliver',
        ),
    ]
