# Generated by Django 4.1.5 on 2023-02-11 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_rename_paper_id_t_user_erja_paper_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_user_erja',
            old_name='paper',
            new_name='paper_erja',
        ),
        migrations.RenameField(
            model_name='t_user_erja',
            old_name='user_deliver',
            new_name='user_deliver_erja',
        ),
    ]
