# Generated by Django 4.1.5 on 2023-02-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_input_paper',
            name='photo_paper',
        ),
        migrations.AddField(
            model_name='t_input_paper',
            name='content_paper',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='t_input_paper',
            name='date_deliver',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='t_input_paper',
            name='no_paper_deliver',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
