# Generated by Django 4.1.5 on 2023-02-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_t_user_erja_paper_erja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_input_paper',
            name='date_paper_see',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='t_input_paper',
            name='mozo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='t_input_paper',
            name='peyvast',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='t_input_paper',
            name='tozihat',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
