# Generated by Django 4.1.5 on 2023-02-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_t_sign_digital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_sign_digital',
            old_name='photo_dsign',
            new_name='photo_sign',
        ),
    ]
