# Generated by Django 4.1.5 on 2023-02-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_t_user_permination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_user_permination',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
