# Generated by Django 4.1.5 on 2023-02-24 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0023_alter_t_user_permination_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_user_permination',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perm_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
